### ISSUE TITLE
some python dependencies are missing

### ISSUE THREAD

**Issue by Tset-Noitamotua** [fisodd/hugo-restructured#1]
Thank you for this great work!

It's worth to mention in readme that some python modules are required:

```
# (optional) virtualenv venv
pip install docutils
pip install pygments

# without virtualenv
pip install --user docutils
pip install --user pygments
```

**Comment by fisodd** [comment]
Good point @Tset-Noitamotua

I'll go add something for this, but probably try to keep it short (the readme is already long...)
